FROM ethereum/solc:0.6.4-alpine

RUN apk add --d --no-cache ca-certificates npm nodejs bash alpine-sdk

RUN git clone https://github.com/bnb-chain/bsc-genesis-contract.git /root/genesis \
    && rm /root/genesis/package-lock.json && cd /root/genesis && npm install

COPY scripts/init_holders.template /root/genesis/init_holders.template

COPY --from=bsc-geth:docker-local /usr/local/bin/geth /usr/local/bin/geth

ENTRYPOINT [ "/bin/bash" ]