FROM golang:1.20.4

ARG GIT_SOURCE
ARG GIT_CHECKOUT_REF

RUN apt update && apt install make gcc libc-dev binutils-gold musl-dev git build-essential -y

RUN cd / && git clone ${GIT_SOURCE} \
    && cd ./bsc && git checkout ${GIT_CHECKOUT_REF} && make geth

RUN mv /bsc/build/bin/geth /usr/local/bin/

EXPOSE 30311 30311/udp